In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
%pylab inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Populating the interactive namespace from numpy and matplotlib


In [10]:
import torchvision 
import torch
import sys
import os
import pandas as pd

In [11]:
import scipy.io as sio

## ILSVRC-2012

In [71]:
meta_mat_path = "../data/ilsvrc2012/ILSVRC2012_devkit_t12/data/meta.mat"
val_gt_path  ="../data/ilsvrc2012/ILSVRC2012_devkit_t12/data/ILSVRC2012_validation_ground_truth.txt"
meta_file_path = "../data/ilsvrc2012/meta.bin"

In [68]:
def parse_meta_mat(path):
    meta = sio.loadmat(path, squeeze_me=True)["synsets"]
    nums_children = list(zip(*meta))[4]
    meta = [meta[idx] for idx, num_children in enumerate(nums_children)
            if num_children == 0]
    idcs, wnids, classes = list(zip(*meta))[:3]
    classes = [tuple(clss.split(", ")) for clss in classes]
    idx_to_wnid = {idx: wnid for idx, wnid in zip(idcs, wnids)}
    wnid_to_classes = {wnid: clss for wnid, clss in zip(wnids, classes)}
    return idx_to_wnid, wnid_to_classes

In [73]:
def parse_val_groundtruth_txt(path):
    with open(path, "r") as txtfh:
        val_idcs = txtfh.readlines()
    return [int(val_idx) for val_idx in val_idcs]

In [74]:
idx_to_wnid, wnid_to_classes = parse_meta_mat(meta_mat_path)
val_idcs = parse_val_groundtruth_txt(val_gt_path)
val_wnids = [idx_to_wnid[idx] for idx in val_idcs]
torch.save((wnid_to_classes, val_wnids), meta_file_path)

In [82]:
list(idx_to_wnid.keys()).sort()

In [88]:
keys = idx_to_wnid.keys()
list(keys).sort()
for idx, key in enumerate(keys, 1):
    if idx == 1 or idx == 1000:
        continue
    if idx_to_wnid[idx] > idx_to_wnid[idx+1]:
        print("No")
        print(idx, idx_to_wnid[idx])
        print(idx+1, idx_to_wnid[idx+1])
        break

No
3
3 n02110185
4 n02096294


{'n02119789': ('kit fox', 'Vulpes macrotis'),
 'n02100735': ('English setter',),
 'n02110185': ('Siberian husky',),
 'n02096294': ('Australian terrier',),
 'n02102040': ('English springer', 'English springer spaniel'),
 'n02066245': ('grey whale',
  'gray whale',
  'devilfish',
  'Eschrichtius gibbosus',
  'Eschrichtius robustus'),
 'n02509815': ('lesser panda',
  'red panda',
  'panda',
  'bear cat',
  'cat bear',
  'Ailurus fulgens'),
 'n02124075': ('Egyptian cat',),
 'n02417914': ('ibex', 'Capra ibex'),
 'n02123394': ('Persian cat',),
 'n02125311': ('cougar',
  'puma',
  'catamount',
  'mountain lion',
  'painter',
  'panther',
  'Felis concolor'),
 'n02423022': ('gazelle',),
 'n02346627': ('porcupine', 'hedgehog'),
 'n02077923': ('sea lion',),
 'n02110063': ('malamute', 'malemute', 'Alaskan malamute'),
 'n02447366': ('badger',),
 'n02109047': ('Great Dane',),
 'n02089867': ('Walker hound', 'Walker foxhound'),
 'n02102177': ('Welsh springer spaniel',),
 'n02091134': ('whippet',),
 '

In [8]:
ab_map_txt = os.path.join(imagenet_dir, map_txt_path)
map_txt = pd.read_csv(ab_map_txt, sep=" ", header=None)

In [9]:
map_txt

0     1                   2
0    n02119789     1             kit_fox
1    n02100735     2      English_setter
2    n02110185     3      Siberian_husky
3    n02096294     4  Australian_terrier
4    n02102040     5    English_springer
..         ...   ...                 ...
995  n03063599   996          coffee_mug
996  n04116512   997       rubber_eraser
997  n04325704   998               stole
998  n07831146   999           carbonara
999  n03255030  1000            dumbbell

[1000 rows x 3 columns]

In [3]:
vgg = torchvision.models.vgg16()

In [4]:
for name, param in vgg.named_parameters():
    print(name, param.size())

features.0.weight torch.Size([64, 3, 3, 3])
features.0.bias torch.Size([64])
features.2.weight torch.Size([64, 64, 3, 3])
features.2.bias torch.Size([64])
features.5.weight torch.Size([128, 64, 3, 3])
features.5.bias torch.Size([128])
features.7.weight torch.Size([128, 128, 3, 3])
features.7.bias torch.Size([128])
features.10.weight torch.Size([256, 128, 3, 3])
features.10.bias torch.Size([256])
features.12.weight torch.Size([256, 256, 3, 3])
features.12.bias torch.Size([256])
features.14.weight torch.Size([256, 256, 3, 3])
features.14.bias torch.Size([256])
features.17.weight torch.Size([512, 256, 3, 3])
features.17.bias torch.Size([512])
features.19.weight torch.Size([512, 512, 3, 3])
features.19.bias torch.Size([512])
features.21.weight torch.Size([512, 512, 3, 3])
features.21.bias torch.Size([512])
features.24.weight torch.Size([512, 512, 3, 3])
features.24.bias torch.Size([512])
features.26.weight torch.Size([512, 512, 3, 3])
features.26.bias torch.Size([512])
features.28.weight t

In [7]:
csv_dir = "../data/Caltech101/csv"

In [12]:
for file in os.listdir(csv_dir):
    path = os.path.join(csv_dir, file)
    csvfile = pd.read_csv(path, header=None)
    print(path, csvfile.values.shape[0])
    break

../data/Caltech101/csv/caltech101_train_subset4.csv 3030


In [15]:
csvfile

0
0        Faces/image_0226.jpg
1        Faces/image_0190.jpg
2        Faces/image_0011.jpg
3        Faces/image_0012.jpg
4        Faces/image_0287.jpg
5        Faces/image_0415.jpg
6        Faces/image_0147.jpg
7        Faces/image_0174.jpg
8        Faces/image_0266.jpg
9        Faces/image_0383.jpg
10       Faces/image_0316.jpg
11       Faces/image_0063.jpg
12       Faces/image_0153.jpg
13       Faces/image_0189.jpg
14       Faces/image_0051.jpg
15       Faces/image_0332.jpg
16       Faces/image_0414.jpg
17       Faces/image_0138.jpg
18       Faces/image_0284.jpg
19       Faces/image_0334.jpg
20       Faces/image_0430.jpg
21       Faces/image_0092.jpg
22       Faces/image_0289.jpg
23       Faces/image_0062.jpg
24       Faces/image_0126.jpg
25       Faces/image_0027.jpg
26       Faces/image_0432.jpg
27       Faces/image_0200.jpg
28       Faces/image_0398.jpg
29       Faces/image_0246.jpg
...                       ...
3000  yin_yang/image_0029.jpg
3001  yin_yang/image_0039.jpg
3002  yin_yang/image_0005.jpg
3003  yin_yang/image_0034.jpg
3004  yin_yang/image_0038.jpg
3005  yin_yang/image_0057.jpg
3006  yin_yang/image_0012.jpg
3007  yin_yang/image_0051.jpg
3008  yin_yang/image_0002.jpg
3009  yin_yang/image_0045.jpg
3010  yin_yang/image_0058.jpg
3011  yin_yang/image_0030.jpg
3012  yin_yang/image_0042.jpg
3013  yin_yang/image_0010.jpg
3014  yin_yang/image_0046.jpg
3015  yin_yang/image_0014.jpg
3016  yin_yang/image_0060.jpg
3017  yin_yang/image_0040.jpg
3018  yin_yang/image_0044.jpg
3019  yin_yang/image_0018.jpg
3020  yin_yang/image_0035.jpg
3021  yin_yang/image_0054.jpg
3022  yin_yang/image_0053.jpg
3023  yin_yang/image_0037.jpg
3024  yin_yang/image_0048.jpg
3025  yin_yang/image_0022.jpg
3026  yin_yang/image_0016.jpg
3027  yin_yang/image_0006.jpg
3028  yin_yang/image_0004.jpg
3029  yin_yang/image_0026.jpg

[3030 rows x 1 columns]

In [25]:
v = csvfile.values

In [27]:
for row in v:
    print(row)

['Faces/image_0226.jpg']
['Faces/image_0190.jpg']
['Faces/image_0011.jpg']
['Faces/image_0012.jpg']
['Faces/image_0287.jpg']
['Faces/image_0415.jpg']
['Faces/image_0147.jpg']
['Faces/image_0174.jpg']
['Faces/image_0266.jpg']
['Faces/image_0383.jpg']
['Faces/image_0316.jpg']
['Faces/image_0063.jpg']
['Faces/image_0153.jpg']
['Faces/image_0189.jpg']
['Faces/image_0051.jpg']
['Faces/image_0332.jpg']
['Faces/image_0414.jpg']
['Faces/image_0138.jpg']
['Faces/image_0284.jpg']
['Faces/image_0334.jpg']
['Faces/image_0430.jpg']
['Faces/image_0092.jpg']
['Faces/image_0289.jpg']
['Faces/image_0062.jpg']
['Faces/image_0126.jpg']
['Faces/image_0027.jpg']
['Faces/image_0432.jpg']
['Faces/image_0200.jpg']
['Faces/image_0398.jpg']
['Faces/image_0246.jpg']
['Faces_easy/image_0232.jpg']
['Faces_easy/image_0404.jpg']
['Faces_easy/image_0273.jpg']
['Faces_easy/image_0062.jpg']
['Faces_easy/image_0121.jpg']
['Faces_easy/image_0278.jpg']
['Faces_easy/image_0101.jpg']
['Faces_easy/image_0256.jpg']
['Faces_ea

['yin_yang/image_0044.jpg']
['yin_yang/image_0018.jpg']
['yin_yang/image_0035.jpg']
['yin_yang/image_0054.jpg']
['yin_yang/image_0053.jpg']
['yin_yang/image_0037.jpg']
['yin_yang/image_0048.jpg']
['yin_yang/image_0022.jpg']
['yin_yang/image_0016.jpg']
['yin_yang/image_0006.jpg']
['yin_yang/image_0004.jpg']
['yin_yang/image_0026.jpg']


In [4]:
import math

In [31]:
math.sqrt(6)

2.449489742783178

In [32]:
torch.norm(torch.ones(2,3))

tensor(2.4495)

In [33]:
torch.norm(torch.ones(6 ))

tensor(2.4495)

In [34]:
1 / np.sqrt(6)

0.4082482904638631

In [3]:
math.sqrt(0.5*0.5*224*224)/(224*224)

0.002232142857142857

In [11]:
math.sqrt(0.04)

0.2

In [12]:
224*224

50176

In [1]:
a = 44/5

In [2]:
a

8.8

SyntaxError: invalid syntax (<ipython-input-8-440f0141a24c>, line 1)

In [9]:
7900/(224*224)

0.15744579081632654

In [10]:
0.15/1

0.15

In [14]:
(0.15) * (1/0.3202951) + 0.54

1.0083181228810556

In [5]:
a = torch.tensor([1.0,2,3,-4]).requires_grad_(True)

In [6]:
b = torch.mean(a ** 2 )

In [7]:
b.backward()

In [8]:
a.grad

tensor([ 0.5000,  1.0000,  1.5000, -2.0000])

In [9]:
torch.nn.utils.clip_grad_norm_(a, max_norm=1, norm_type=inf)

tensor(2.)

In [10]:
a.grad

tensor([ 0.2500,  0.5000,  0.7500, -1.0000])

In [7]:
??torch.range(10)


Object `torch.range(10)` not found.


In [27]:
a = torch.range(0, 9).view(2,5)
a = a.gt(0)

/Users/lincolnzjx/opt/anaconda3/envs/Py37/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


In [28]:
b = torch.randint(10, (2,5))
print(b)

tensor([[4, 4, 3, 9, 2],
        [9, 8, 7, 4, 6]])


In [29]:
a * b

tensor([[0, 4, 3, 9, 2],
        [9, 8, 7, 4, 6]])

In [31]:
~a

tensor([[ True, False, False, False, False],
        [False, False, False, False, False]])