In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import torchvision
import numpy as np
import torchvision.transforms as transforms
import sys
sys.path.append('../src')
import dataset

# Calculate mean, std for torchvision's cifar10, cifar100, MNIST

In [3]:
def gen_mean_std(dataset, ratio=0.01):
    """sample 0.1
    """
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=int(len(dataset)*ratio), shuffle=True, num_workers=10)
    train = iter(dataloader).next()[0]
    mean = np.mean(train.numpy(), axis=(0,2,3))
    std = np.std(train.numpy(), axis=(0,2,3))
    return mean, std

# Differen Dataset

In [4]:
# caltech 
train_dataset = dataset.Caltech101(root="../data", is_train=True, transform=transforms.Compose([
            transforms.Resize((224,224)),
            transforms.ToTensor()
        ]))
train_mean, train_std = gen_mean_std(train_dataset, ratio=1)
print(train_mean, train_std)

[0.54959273 0.52337575 0.49149838] [0.32029507 0.31704384 0.3272979 ]


In [18]:
# cifar10
train_dataset = torchvision.datasets.CIFAR10('../data', train=True, download=True, transform=transforms.Compose([transforms.ToTensor()]))
train_mean, train_std = gen_mean_std(train_dataset)
print(train_mean, train_std)

Files already downloaded and verified
[0.48915905 0.47926533 0.44592172] [0.24737428 0.24498263 0.2618268 ]


In [30]:
# cifar100
train_dataset = torchvision.datasets.CIFAR100('../data', train=True, download=True, transform=transforms.Compose([transforms.ToTensor()]))
train_mean, train_std = gen_mean_std(train_dataset)
print(train_mean, train_std)

Files already downloaded and verified
[0.49604437 0.48263332 0.43671504] [0.27043936 0.2545973  0.27637145]


In [ ]:
# Mini-ImageNet
train_dataset = torchvision.datasets.ImageFolder('../data/miniImageNet/train/', transform=transforms.Compose([
            transforms.Resize((224,224)),
            transforms.ToTensor()
        ]))
train_mean, train_std = gen_mean_std(train_dataset)
print(train_mean, train_std)

In [5]:
# sd-198 1
train_dataset = datasets.SpecificDataset(dataset_name='SD198', data_augmentation=False, iter_no=0).train_dataset
train_mean, train_std = gen_mean_std(train_dataset, ratio=0.1)
print(train_mean, train_std)

[0.5921026  0.47901225 0.45117727] [0.26520276 0.24511227 0.24672566]


In [27]:
# sd-198 2
train_dataset = datasets.SpecificDataset(dataset_name='SD198', data_augmentation=False, iter_no=1).train_dataset
train_mean, train_std = gen_mean_std(train_dataset, ratio=0.01)
print(train_mean, train_std)

[0.25338554 0.08627725 0.01029419] [0.91431177 0.9481566  0.9131112 ]


In [28]:
# sd-198 3
train_dataset = datasets.SpecificDataset(dataset_name='SD198', data_augmentation=False, iter_no=2).train_dataset
train_mean, train_std = gen_mean_std(train_dataset, ratio=0.01)
print(train_mean, train_std)

[0.10649281 0.03926077 0.06205735] [0.88490963 0.8685787  0.8774559 ]


In [29]:
# sd-198 4
train_dataset = datasets.SpecificDataset(dataset_name='SD198', data_augmentation=False, iter_no=3).train_dataset
train_mean, train_std = gen_mean_std(train_dataset, ratio=0.01)
print(train_mean, train_std)

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc89b2bd0f0>>
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc89b2bd0f0>>
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc89b2bd0f0>>
Traceback (most recent call last):
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
Traceback (most recent call last):
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
    self._shutdown_workers()
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
Traceback (most recent call last):
  File "/home/lincolnzjx/anaconda3/envs/P

[ 0.03861747 -0.01254432 -0.04720071] [0.94373405 0.91663104 0.9304368 ]


In [30]:
# sd-198 5
train_dataset = datasets.SpecificDataset(dataset_name='SD198', data_augmentation=False, iter_no=4).train_dataset
train_mean, train_std = gen_mean_std(train_dataset, ratio=0.01)
print(train_mean, train_std)

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc89b2bd0f0>>
Traceback (most recent call last):
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc89b2bd0f0>>
    self._shutdown_workers()
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/multiprocessing/process.py", line 122, in join
Traceback (most recent call last):
    assert self._parent_pid == os.getpid(), 'can only join a child process'
  File "/home/lincolnzjx/anaconda3/envs/Py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
AssertionError: can only join a child process

[ 0.15823184  0.02122124 -0.01373529] [0.9062277 0.900465  0.9045457]
