In [1]:
import torch

In [2]:
a = torch.tensor([[0,0,1],[0,0,1]])
b = torch.randn(2,3)

In [3]:
a * b

tensor([[-0.0000,  0.0000,  1.3263],
        [-0.0000,  0.0000, -1.1101]])

In [4]:
b

tensor([[-0.0878,  0.2084,  1.3263],
        [-0.8315,  0.7175, -1.1101]])

In [5]:
b.le(0)

tensor([[ True, False, False],
        [ True, False,  True]])

In [8]:
torch.relu(b)

tensor([[0.0000, 0.2084, 1.3263],
        [0.0000, 0.7175, 0.0000]])

In [9]:
torch.relu(b).le(0)

tensor([[ True, False, False],
        [ True, False,  True]])